image: python:3.6-alpine

stages:
  - build

build:
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    APP_TAG: $CI_REGISTRY_IMAGE/app:$CI_COMMIT_SHA
    APP_LAST: $CI_REGISTRY_IMAGE/app:latest
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --pull --cache-from $APP_LAST --tag $APP_TAG --tag $APP_LAST -f ./Dockerfile .
    - docker push $APP_TAG
    - docker push $APP_LAST
    - echo $CI_COMMIT_SHA
  dependencies: []
  only:
    - master
    - staging
